---
title: "Gapminder Part 2"
format:
  html:
    keep-md: true
editor: visual
---

```{r}
#install.packages("devtools")
library(gapminder)
library(tidyverse)
library(ggplot2)


```

```{r}
# Remove Kuwait from the dataset
gapminder <- gapminder %>% filter(country != "Kuwait")

```

```{r}

head(gapminder)

```

```{r}


data_filtered <- gapminder %>%
  filter(continent %in% c("Africa", "Americas", "Asia", "Europe", "Oceania"))


weighted_avg_data <- data_filtered %>%
  group_by(year, continent) %>%
  summarise(weighted_gdp = weighted.mean(gdpPercap, w = pop / 100000), .groups = "drop")


ggplot(data_filtered, aes(x = year, y = gdpPercap, color = continent, size = pop / 100000)) +
  geom_point(alpha = 0.7) +
  labs(size = "Population (100k)",
       x = "Year",
       y = "GDP per Capita") +
  scale_x_continuous(breaks = seq(1950, 2000, by = 10)) +
  scale_y_continuous(breaks = seq(0, 50000, by = 10000), limits = c(0, 50000)) +
  theme_bw() +
  facet_wrap(~continent, nrow = 1) +
  theme(strip.text = element_text(size = 12)) +
  

  geom_line(aes(group = interaction(continent, country), color = continent), alpha = 0.7, size = 1) +
  geom_point(aes(group = interaction(continent, country), color = continent), alpha = 0.7, size = 3) +
  

  geom_line(data = weighted_avg_data, aes(group = continent, x = year, y = weighted_gdp), 
            color = "black", size = 1) +
  geom_point(data = weighted_avg_data, aes(group = continent, x = year, y = weighted_gdp), 
             color = "black", size = 3) +
  

  scale_size_continuous(breaks = c(10000, 20000, 30000), labels = c("10000", "20000", "30000"), limits = c(10000, 30000)) +
  

  scale_linewidth(range = c(0.5, 2))  # Adjust the range as needed


```
